// PDF Export utility using browser APIs
export async function exportResultsToPDF(
  results: any,
  className: string,
  exportDate: string
) {
  // For now, we'll create a formatted HTML that can be printed to PDF
  // In production, you might want to use a library like jsPDF or pdfmake
  
  const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <title>Election Results - ${className}</title>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Display', sans-serif;
            padding: 40px;
            color: #1d1d1f;
            background: white;
          }
          h1 {
            font-size: 32px;
            font-weight: 600;
            margin-bottom: 8px;
          }
          h2 {
            font-size: 24px;
            font-weight: 600;
            margin-top: 32px;
            margin-bottom: 16px;
            border-bottom: 2px solid #007AFF;
            padding-bottom: 8px;
          }
          .meta {
            color: #86868b;
            font-size: 14px;
            margin-bottom: 32px;
          }
          .position {
            margin-bottom: 32px;
            page-break-inside: avoid;
          }
          .candidate {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 12px 0;
            border-bottom: 1px solid #e5e5e7;
          }
          .candidate-name {
            font-weight: 500;
            font-size: 16px;
          }
          .candidate-votes {
            color: #007AFF;
            font-weight: 600;
            font-size: 16px;
          }
          .winner {
            background: #f0f9ff;
            padding: 12px;
            border-radius: 8px;
            margin-top: 8px;
          }
          .winner-badge {
            display: inline-block;
            background: #007AFF;
            color: white;
            padding: 4px 12px;
            border-radius: 12px;
            font-size: 12px;
            font-weight: 600;
            margin-left: 8px;
          }
          @media print {
            body { padding: 20px; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <h1>Election Results</h1>
        <div class="meta">
          <div>Class: ${className}</div>
          <div>Export Date: ${exportDate}</div>
        </div>
        
        ${Object.values(results).map((result: any) => `
          <div class="position">
            <h2>${result.position.title}</h2>
            ${result.candidates.map((candidate: any, index: number) => `
              <div class="candidate ${index === 0 && candidate.voteCount > 0 ? 'winner' : ''}">
                <div>
                  <span class="candidate-name">${candidate.candidateName}</span>
                  ${index === 0 && candidate.voteCount > 0 ? '<span class="winner-badge">WINNER</span>' : ''}
                </div>
                <div class="candidate-votes">
                  ${candidate.voteCount} votes (${((candidate.voteCount / result.totalVotes) * 100).toFixed(1)}%)
                </div>
              </div>
            `).join('')}
            <div style="margin-top: 12px; color: #86868b; font-size: 14px;">
              Total Votes: ${result.totalVotes}
            </div>
          </div>
        `).join('')}
        
        <div style="margin-top: 48px; padding-top: 24px; border-top: 2px solid #e5e5e7; color: #86868b; font-size: 12px; text-align: center;">
          <div>Generated by VoteSecure - Blockchain-Secured Voting System</div>
          <div style="margin-top: 4px;">This document is a verified record of election results</div>
        </div>
      </body>
    </html>
  `;

  // Open in new window for printing
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    
    // Wait for content to load, then trigger print
    setTimeout(() => {
      printWindow.print();
    }, 250);
  } else {
    // Fallback: create download link
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `election-results-${className}-${exportDate}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }
}









